[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "enrich_lerobot_dataset"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "roboto>=0.30.0",
    "lerobot>=0.4.0,<0.5.1",
    "numpy"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff~=0.16.8",
]
