"""Render a contract into a runnable ``rclpy.Node`` source string.

The codegen layer has two halves: the CLI in :mod:`cli` (load,
validate, dispatch) and this module (turn a validated contract into
Python source). They live separately so the rendering path can be
unit-tested without going through argparse.

The generated file shape is fixed; the test suite asserts that shape
is preserved and that the rendered source parses cleanly via
:func:`ast.parse`. ``black`` runs
as an optional post-pass — if installed (the ``codegen`` / ``dev``
extras carry it), the output is reformatted; if not, the unformatted
source is still valid Python and ships as-is. ``jinja2`` (required to
render) and ``black`` both live in the optional ``codegen`` extra
rather than core deps, so a live-inference-only install stays lean.

QoS defaults are a codegen-only concern (by design:
the runtime kernel does not know about QoS). Sensor-shaped topics
(image, PointCloud) get ``BEST_EFFORT/KEEP_LAST/1``; everything else
gets ``RELIABLE/KEEP_LAST/10``. An explicit ``qos:`` block on a spec
always wins via an inline ``QoSProfile`` per subscription/publisher.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import jinja2

from ..contract_utils import ObservationSpec, QosSpec
from ..runtime.contract_io import Contract

# Codegen version baked into every generated file's header. Bump when
# the template output shape changes in a way users should
# regenerate against — the value also lets future tooling refuse
# files generated by an old codegen if a runtime incompat lands.
CODEGEN_VERSION = "0.1.0"


class RenderError(Exception):
    """Raised when rendering cannot proceed (e.g. a missing codegen dependency).

    Distinct from ``cli.GenNodeError`` so this module stays free of any
    import back into the CLI; ``cli.main`` catches both and maps them to
    the same non-zero exit.
    """


# Message types that ROS 2 publishers default to ``BEST_EFFORT`` on
# Humble. Compared in lowercase against the trailing segment of the
# spec's ``type`` (``sensor_msgs/msg/Image`` → ``image``). Any spec
# whose type is not in this set falls into the ``RELIABLE`` bucket.
_SENSOR_TYPE_LAST_SEGMENT: frozenset[str] = frozenset({
    "image",
    "compressedimage",
    "pointcloud",
    "pointcloud2",
})


@dataclass(frozen=True)
class _SubscriptionView:
    """Template-facing record for one ``create_subscription`` call.

    ``msg_class`` is the short class name (``JointState``); the import
    side of the template knows its module path. ``callback_method`` is
    the sanitized Python identifier of the bound method that forwards
    to ``adapter.on_message`` — derived from the contract topic so two
    observations sharing a topic still produce one subscription.
    ``qos_inline`` is either ``None`` (template uses a shared profile
    by ``qos_kind``) or a literal ``QoSProfile(...)`` expression
    composed from an explicit ``qos:`` block.
    """

    topic: str
    msg_class: str
    callback_method: str
    qos_kind: str  # "sensor" | "reliable"
    qos_inline: str | None


@dataclass(frozen=True)
class _PublisherView:
    """Template-facing record for one ``create_publisher`` call."""

    topic: str
    msg_class: str
    attr: str
    qos_kind: str
    qos_inline: str | None


@dataclass(frozen=True)
class _ImportView:
    """One ``from X import Y`` for a ROS message class."""

    module: str
    cls: str


# ---------------------------------------------------------------------------
# Public render entry point
# ---------------------------------------------------------------------------


def render_node(
    contract: Contract,
    *,
    policy_module: str,
    manifest_path: Path,
    node_class_name: str | None = None,
    apply_black: bool = True,
) -> str:
    """Render a generated ROS 2 node as a Python source string.

    The contract is assumed to have passed
    :func:`codegen.cli.validate_contract_for_codegen` already — this
    function does not re-check refuse-listed features and will happily
    emit a syntactically-valid file that the runtime would later
    reject. Keep the CLI as the validation gate.

    ``apply_black`` defaults to True; falls through silently to the
    unformatted source when ``black`` is not installed (the ``codegen``
    / ``dev`` extras carry it). The unformatted source is still valid
    Python; formatting is a readability nicety, not a correctness
    gate.
    """
    class_name = node_class_name or _derive_node_name(contract.name)
    context = _build_context(
        contract=contract,
        policy_module=policy_module,
        manifest_path=manifest_path,
        node_class_name=class_name,
    )
    source = _render_template(context)
    if apply_black:
        source = _maybe_format_with_black(source)
    return source


# ---------------------------------------------------------------------------
# Context building
# ---------------------------------------------------------------------------


def _build_context(
    *,
    contract: Contract,
    policy_module: str,
    manifest_path: Path,
    node_class_name: str,
) -> dict[str, Any]:
    """Materialize the dict the Jinja template iterates over.

    All decision-making (QoS dispatch, identifier sanitization, import
    deduplication) happens here so the template is straight-line
    Python emission with zero branching logic.
    """
    obs_specs: list[ObservationSpec] = list(contract.observations) + list(contract.videos)

    subscriptions: list[_SubscriptionView] = []
    seen_sub_topics: dict[str, _SubscriptionView] = {}
    used_callback_names: set[str] = set()
    for spec in obs_specs:
        # Two specs that share a topic ⇒ one ROS subscription whose
        # callback forwards to LiveAdapter.on_message; the adapter
        # fans the message out to every spec internally.
        if spec.topic in seen_sub_topics:
            continue
        view = _SubscriptionView(
            topic=spec.topic,
            msg_class=_msg_class_name(spec.type),
            callback_method=_unique_identifier(
                _callback_method_name(spec.topic), used_callback_names
            ),
            qos_kind=_qos_kind_for_spec(spec),
            qos_inline=_qos_inline(spec.qos),
        )
        subscriptions.append(view)
        seen_sub_topics[spec.topic] = view

    publishers: list[_PublisherView] = []
    seen_pub_topics: dict[str, _PublisherView] = {}
    used_publisher_attrs: set[str] = set()
    for spec in contract.actions:
        if spec.topic in seen_pub_topics:
            continue
        view = _PublisherView(
            topic=spec.topic,
            msg_class=_msg_class_name(spec.type),
            attr=_unique_identifier(
                _publisher_attr(spec.topic), used_publisher_attrs
            ),
            qos_kind=_qos_kind_for_spec(spec),
            qos_inline=_qos_inline(spec.qos),
        )
        publishers.append(view)
        seen_pub_topics[spec.topic] = view

    imports = _dedupe_imports(
        [_import_view_for_type(spec.type) for spec in obs_specs]
        + [_import_view_for_type(spec.type) for spec in contract.actions]
    )

    return {
        "node_class_name": node_class_name,
        "contract_name": contract.name,
        "contract_sha256": _contract_sha256(contract),
        "codegen_version": CODEGEN_VERSION,
        "fps": contract.fps,
        "policy_module": policy_module,
        "default_contract_path": str(contract.source_path),
        "default_manifest_path": str(manifest_path),
        "ros_imports": imports,
        "subscriptions": subscriptions,
        "publishers": publishers,
        # Both shared-profile names are always emitted; if a particular
        # template invocation never references one, the unused profile
        # is dead-code, which black tolerates. Keeping them
        # unconditional simplifies the template and lets a future spec
        # gain a sensor/reliable subscription without re-running
        # codegen for an unrelated branch.
    }


# ---------------------------------------------------------------------------
# Sanitizers + QoS dispatch
# ---------------------------------------------------------------------------


def _derive_node_name(contract_name: str) -> str:
    """``pickplace`` → ``PickplaceInferenceNode`` (default class name).

    Non-identifier chars become word breaks so a contract called
    ``arm-30hz`` still produces a valid Python class name.
    """
    parts = re.split(r"[\W_]+", contract_name)
    camel = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not camel:
        camel = "Generated"
    return f"{camel}InferenceNode"


def _unique_identifier(base: str, used: set[str]) -> str:
    """Return ``base``, or ``base_2`` / ``base_3`` … if it's already taken.

    ``_callback_method_name`` / ``_publisher_attr`` collapse every run
    of non-identifier characters to a single ``_``, so distinct topics
    (``/robot/joint_states``, ``/robot/joint-states``,
    ``/robot/joint/states``) can sanitize to the *same* identifier.
    Dedup keys on the raw topic, so those topics survive as separate
    subscriptions/publishers — without this suffixing the template
    would emit two methods of the same name and Python would keep only
    the last, silently mis-wiring one topic onto another's spec. Mutates
    ``used`` so the caller accumulates the claimed names across a run.
    """
    if base not in used:
        used.add(base)
        return base
    n = 2
    while f"{base}_{n}" in used:
        n += 1
    name = f"{base}_{n}"
    used.add(name)
    return name


def _callback_method_name(topic: str) -> str:
    """``/robot/joint_states`` → ``_on_robot_joint_states``.

    Strips leading slashes and collapses runs of non-identifier chars
    to single underscores. Keeps method names readable while
    guaranteeing they're valid Python identifiers. Callers disambiguate
    collisions via :func:`_unique_identifier`.
    """
    body = re.sub(r"[^A-Za-z0-9]+", "_", topic).strip("_").lower()
    if not body:
        body = "topic"
    return f"_on_{body}"


def _publisher_attr(topic: str) -> str:
    """``/teleop/action`` → ``_pub_teleop_action``."""
    body = re.sub(r"[^A-Za-z0-9]+", "_", topic).strip("_").lower()
    if not body:
        body = "topic"
    return f"_pub_{body}"


def _msg_class_name(type_str: str) -> str:
    """``sensor_msgs/msg/JointState`` → ``JointState``."""
    return type_str.split("/")[-1]


def _import_view_for_type(type_str: str) -> _ImportView:
    """``sensor_msgs/msg/JointState`` → from sensor_msgs.msg import JointState."""
    parts = type_str.split("/")
    if len(parts) < 2:
        # Bare ``video`` / ``avi_video`` / ``mp4_video`` / ``string_typed_msg``
        # are file-backed/offline-only shapes with no ROS message class.
        # ``cli.validate_contract_for_codegen`` (via
        # ``_refuse_unsupported_observation``) refuses these before render,
        # so this branch is unreachable on the CLI path. It survives only
        # as a defensive fallback for a direct ``render_node`` call on an
        # unvalidated contract: map to a synthetic import so the output
        # still parses rather than raising mid-template.
        return _ImportView(module="builtins", cls=type_str)
    cls = parts[-1]
    module = ".".join(parts[:-1])
    return _ImportView(module=module, cls=cls)


def _dedupe_imports(items: Sequence[_ImportView]) -> list[_ImportView]:
    """Stable-order dedup so codegen output is bit-stable across runs."""
    seen: set[tuple[str, str]] = set()
    out: list[_ImportView] = []
    for item in items:
        key = (item.module, item.cls)
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def _qos_kind_for_spec(spec) -> str:
    """Return ``"sensor"`` or ``"reliable"`` based on the message type.

    Used by the template only when the spec has no explicit ``qos:``
    block; an explicit block bypasses this and emits an inline
    ``QoSProfile``.
    """
    last = _msg_class_name(spec.type).lower()
    return "sensor" if last in _SENSOR_TYPE_LAST_SEGMENT else "reliable"


def _qos_inline(qos: QosSpec | None) -> str | None:
    """Render an explicit QoS block as a literal ``QoSProfile(...)`` call.

    Returns ``None`` when no override is set; the template then uses
    the shared sensor/reliable profile via ``qos_kind``. Returning a
    string (not a partial AST) lets the template embed the call
    verbatim — black tidies the line length.
    """
    if qos is None:
        return None
    return (
        "QoSProfile("
        f"reliability=ReliabilityPolicy.{qos.reliability}, "
        f"history=HistoryPolicy.{qos.history}, "
        f"depth={qos.depth})"
    )


def _contract_sha256(contract: Contract) -> str:
    """Compute the file-bytes SHA the manifest verifier will compare against.

    Uses the underlying file rather than re-serialising the parsed
    contract — the file bytes are what the converter wrote into
    ``manifest.contract.sha256``.
    """
    return hashlib.sha256(contract.source_path.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Jinja + black plumbing
# ---------------------------------------------------------------------------


def _jinja_env() -> jinja2.Environment:
    try:
        import jinja2
    except ImportError as exc:  # pragma: no cover - exercised via install extras
        raise RenderError(
            "gen-node needs Jinja2, which is not installed. It ships in the "
            "optional codegen extra (live-inference installs skip it): "
            "pip install 'roboto_to_lerobot[codegen]'."
        ) from exc

    env = jinja2.Environment(
        loader=jinja2.PackageLoader("roboto_to_lerobot.codegen", "templates"),
        autoescape=False,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env


def _render_template(context: dict[str, Any]) -> str:
    template = _jinja_env().get_template("rclpy.py.j2")
    return template.render(**context)


def _maybe_format_with_black(source: str) -> str:
    """Reformat with black if installed; otherwise return source unchanged.

    Black is an optional codegen dep — codegen output is valid Python
    without it, so users who only install the runtime kernel can
    still inspect generated files. CI installs the dev extra so the bit-
    stable formatted output is what reviewers see.
    """
    try:
        import black  # type: ignore
    except ImportError:
        return source

    mode = black.Mode(line_length=100, target_versions={black.TargetVersion.PY312})
    return black.format_str(source, mode=mode)
